/**
 * Split the translated listing copy into one plain file per field.
 *
 * Generated rather than hand-maintained. LISTING-TRANSLATIONS.md stays the one
 * place the text is written and reviewed; this turns it into the shape a store
 * form actually wants, which is a file you can open, select all, and paste with
 * no markdown fences to trim around.
 *
 *   store/listings/<locale>/name.txt
 *   store/listings/<locale>/summary.txt
 *   store/listings/<locale>/description.txt
 *
 * The lengths are checked here rather than trusted, because the store rejects on
 * upload and it does it per language: a summary that fits in English is
 * routinely a third longer in German.
 *
 *   node tools/listings.mjs
 */

import fs from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

const ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');
const STORE = path.join(ROOT, 'store');
const OUT = path.join(STORE, 'listings');

/** Tighter of the two stores in each case, so one file serves both. */
const LIMITS = { name: 50, summary: 132 };

/** Pull the body of the fenced block that follows a `**Label**` heading. */
function blockAfter(section, label) {
  const re = new RegExp(`\\*\\*${label}\\*\\*\\s*\\n+\`\`\`\\n([\\s\\S]*?)\\n\`\`\``);
  const m = re.exec(section);
  return m ? m[1].trim() : null;
}

async function main() {
  const translations = await fs.readFile(path.join(STORE, 'LISTING-TRANSLATIONS.md'), 'utf8');
  const listing = await fs.readFile(path.join(STORE, 'LISTING.md'), 'utf8');

  // English keeps its description in LISTING.md beside the review answers, so
  // it is read from there rather than duplicated into the translations file.
  const englishDescription = blockAfter(
    listing.slice(listing.indexOf('## Detailed description')),
    ''
  ) || (/## Detailed description\s*\n+```\n([\s\S]*?)\n```/.exec(listing) || [])[1];

  if (!englishDescription) throw new Error('could not find the English description in LISTING.md');

  const problems = [];
  const rows = [];

  await fs.mkdir(OUT, { recursive: true });

  for (const section of translations.split('\n## ').slice(1)) {
    const heading = section.split('\n')[0].trim();
    const m = /^(.+?)\s*\(([A-Za-z-]+)\)$/.exec(heading);
    if (!m) continue;

    const language = m[1];
    // Underscored to match the _locales folder names, so the two line up.
    const locale = m[2].replace('-', '_');

    const fields = {
      name: blockAfter(section, 'Name'),
      summary: blockAfter(section, 'Summary'),
      description: blockAfter(section, 'Description') || (locale === 'en' ? englishDescription.trim() : null),
    };

    for (const [field, value] of Object.entries(fields)) {
      if (!value) {
        problems.push(`${locale}: no ${field}`);
        continue;
      }
      const limit = LIMITS[field];
      if (limit && value.length > limit) {
        problems.push(`${locale}: ${field} is ${value.length} characters, over ${limit}`);
      }
    }
    if (!fields.name || !fields.summary || !fields.description) continue;

    const dir = path.join(OUT, locale);
    await fs.mkdir(dir, { recursive: true });
    for (const [field, value] of Object.entries(fields)) {
      await fs.writeFile(path.join(dir, `${field}.txt`), value + '\n', 'utf8');
    }

    rows.push({ locale, language, ...Object.fromEntries(Object.entries(fields).map(([k, v]) => [k, v.length])) });
  }

  // Stale locales are pruned one at a time rather than by clearing the whole
  // folder first. On Windows, removing a directory a shell is sitting in fails
  // with EBUSY, and that turns "I renamed a section" into a broken tool.
  const wanted = new Set(rows.map((r) => r.locale));
  for (const entry of await fs.readdir(OUT, { withFileTypes: true })) {
    if (!entry.isDirectory() || wanted.has(entry.name)) continue;
    await fs.rm(path.join(OUT, entry.name), { recursive: true, force: true });
    console.log(`  removed ${entry.name}, which is no longer in the translations file`);
  }

  await fs.writeFile(
    path.join(OUT, 'README.md'),
    [
      '# Listing copy, one file per field',
      '',
      'Generated by `npm run listings` from [../LISTING-TRANSLATIONS.md](../LISTING-TRANSLATIONS.md).',
      'Edit that file, not these. Anything changed here is overwritten on the next run.',
      '',
      'Open a file, select all, paste. No fences to trim.',
      '',
      '| Store | name.txt | summary.txt | description.txt |',
      '| --- | --- | --- | --- |',
      '| Chrome Web Store | Name | Summary | Description |',
      '| Firefox add-ons | Name | Summary | Description |',
      '',
      'Chrome: open the item, pick the language from the dropdown at the top of the',
      'listing editor, paste the three fields, save, repeat. Firefox: Manage Listing,',
      'then "Add a locale" beside the Name field.',
      '',
      'A language with no listing falls back to the default one on both stores, so',
      'there is no penalty for leaving one out.',
      '',
      '| Locale | Language | Name | Summary | Description |',
      '| --- | --- | ---: | ---: | ---: |',
      ...rows.map(
        (r) => `| \`${r.locale}\` | ${r.language} | ${r.name} | ${r.summary} | ${r.description} |`
      ),
      '',
      `Limits: name ${LIMITS.name}, summary ${LIMITS.summary}. Those are the tighter of the two`,
      'stores in each case, so the same text works on both without a second pass.',
      '',
    ].join('\n'),
    'utf8'
  );

  for (const r of rows) {
    console.log(`  ${r.locale.padEnd(6)} ${String(r.name).padStart(4)}  ${String(r.summary).padStart(4)}  ${String(r.description).padStart(6)}  ${r.language}`);
  }
  console.log(`\n${rows.length} listings -> ${path.relative(ROOT, OUT)}`);

  if (problems.length) {
    console.error('\nProblems:\n' + problems.map((p) => `  x ${p}`).join('\n') + '\n');
    process.exit(1);
  }
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
